export type RoleKey =
  | "tourist"
  | "partner"
  | "ambassador"
  | "regional"
  | "admin";

export type ScreenDefinition = {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  role: RoleKey;
};

export const roles: Array<{
  key: RoleKey;
  label: string;
  shortLabel: string;
  description: string;
}> = [
  {
    key: "tourist",
    label: "Турист",
    shortLabel: "Турист",
    description: "Telegram Mini App і ключові сценарії мандрівника",
  },
  {
    key: "partner",
    label: "Партнер",
    shortLabel: "Партнер",
    description: "Власник, менеджер і працівник / касир",
  },
  {
    key: "ambassador",
    label: "Амбасадор",
    shortLabel: "Амбасадор",
    description: "Залучення, кампанії та статус винагород",
  },
  {
    key: "regional",
    label: "Регіональний адмін",
    shortLabel: "Регіон",
    description: "Партнери, контент та статистика свого регіону",
  },
  {
    key: "admin",
    label: "Головна адмінка",
    shortLabel: "Адмін",
    description: "Модерація, QR, фінанси, аудит і керування системою",
  },
];

export const screens: ScreenDefinition[] = [
  {
    id: "C01",
    slug: "welcome",
    title: "QR welcome / контекст входу",
    shortTitle: "QR welcome",
    description: "Джерело QR, регіон, точка входу й продовження",
    role: "tourist",
  },
  {
    id: "C02",
    slug: "home",
    title: "Головний екран туриста",
    shortTitle: "Головна",
    description: "Вісім основних категорій і контекст готелю",
    role: "tourist",
  },
  {
    id: "C03",
    slug: "about",
    title: "Про заклад",
    shortTitle: "Про заклад",
    description: "Правила, Wi‑Fi, послуги, контакти й запити гостя",
    role: "tourist",
  },
  {
    id: "C03A",
    slug: "hotel-services",
    title: "Послуги закладу",
    shortTitle: "Послуги",
    description: "Перелік і детальні картки послуг закладу",
    role: "tourist",
  },
  {
    id: "C04",
    slug: "catalog",
    title: "Категорія / пошук",
    shortTitle: "Каталог",
    description: "Пошук, фільтри, сортування й прозоре маркування",
    role: "tourist",
  },
  {
    id: "C05",
    slug: "nearby",
    title: "Карта / що поруч",
    shortTitle: "Що поруч",
    description: "Карта та список місць у радіусі базової точки",
    role: "tourist",
  },
  {
    id: "C06",
    slug: "place",
    title: "Картка закладу / локації",
    shortTitle: "Картка місця",
    description: "Опис, атрибути, рейтинг, маршрут і бонусні умови",
    role: "tourist",
  },
  {
    id: "C07",
    slug: "available",
    title: "Доступно зараз",
    shortTitle: "Доступно зараз",
    description: "Лише реальні вільні ресурси та актуальні слоти",
    role: "tourist",
  },
  {
    id: "C08",
    slug: "booking",
    title: "Бронювання",
    shortTitle: "Бронювання",
    description: "Дата, ресурс, вільний слот, контакт і підтвердження",
    role: "tourist",
  },
  {
    id: "C09",
    slug: "plan",
    title: "Мій план",
    shortTitle: "Мій план",
    description: "Готові сценарії відпочинку на 1–5 днів",
    role: "tourist",
  },
  {
    id: "C10",
    slug: "wallet",
    title: "Бонусний гаманець",
    shortTitle: "Бонуси",
    description: "Баланс, доступні й очікувані бонуси, історія та строк дії",
    role: "tourist",
  },
  {
    id: "C11",
    slug: "qr",
    title: "Мій QR",
    shortTitle: "Мій QR",
    description: "Одноразовий токен і таймер дії для операції",
    role: "tourist",
  },
  {
    id: "C12",
    slug: "purchase-confirmation",
    title: "Підтвердження QR-операції",
    shortTitle: "Підтвердження",
    description: "Партнер, сума, бонуси й явне підтвердження клієнтом",
    role: "tourist",
  },
  {
    id: "C13",
    slug: "review",
    title: "Перевірений відгук",
    shortTitle: "Відгук",
    description: "Оцінка після підтвердженої транзакції або бронювання",
    role: "tourist",
  },
  {
    id: "C14",
    slug: "emergency",
    title: "Халепа?",
    shortTitle: "Халепа?",
    description: "Екстрені та локальні контакти, геолокація й допомога",
    role: "tourist",
  },
  {
    id: "C15",
    slug: "profile",
    title: "Профіль",
    shortTitle: "Профіль",
    description: "Мова, телефон за згодою, приватність і налаштування",
    role: "tourist",
  },
  {
    id: "C15A",
    slug: "add-location",
    title: "Додати локацію",
    shortTitle: "Додати локацію",
    description: "Вибір і додавання нової локації туристом",
    role: "tourist",
  },
  {
    id: "C16",
    slug: "community",
    title: "Telegram-спільнота",
    shortTitle: "Спільнота",
    description: "Регіональний канал, підтримка та згода на повідомлення",
    role: "tourist",
  },
  {
    id: "C17",
    slug: "shop",
    title: "Де купити",
    shortTitle: "Де купити",
    description: "Магазини, аптеки, сувеніри та корисні товари поруч",
    role: "tourist",
  },
  {
    id: "C18",
    slug: "entertainment",
    title: "Розваги",
    shortTitle: "Розваги",
    description: "Джип-тури, рафтинг, зіплайн та активності в регіоні",
    role: "tourist",
  },
  {
    id: "C19",
    slug: "transfer",
    title: "Трансфер",
    shortTitle: "Трансфер",
    description: "Таксі, міжміські трансфери та оренда автомобілів",
    role: "tourist",
  },
  {
    id: "C20",
    slug: "hot-offers",
    title: "Гарячі пропозиції",
    shortTitle: "Гарячі пропозиції",
    description: "Актуальні знижки та спеціальні пропозиції від партнерів",
    role: "tourist",
  },
  {
    id: "C21",
    slug: "hot-offer-detail",
    title: "Деталі гарячої пропозиції",
    shortTitle: "Пропозиція",
    description: "Деталі знижки, партнер, термін дії та спосіб скористатися",
    role: "tourist",
  },

  {
    id: "P01",
    slug: "partner-dashboard",
    title: "Партнерський dashboard",
    shortTitle: "Dashboard",
    description: "Метрики, бронювання, баланс, рейтинг і швидкі дії",
    role: "partner",
  },
  {
    id: "P01A",
    slug: "partner-onboarding",
    title: "Стати партнером",
    shortTitle: "Стати партнером",
    description: "Заповнення даних закладу перед активацією партнерського кабінету",
    role: "partner",
  },
  {
    id: "P01B",
    slug: "partner-info",
    title: "Інформація про заклад",
    shortTitle: "Інформація",
    description: "Фото, опис, тип закладу, адреса, послуги й базові дані",
    role: "partner",
  },
  {
    id: "P01C",
    slug: "partner-rules",
    title: "Правила проживання",
    shortTitle: "Правила",
    description: "Правила заселення, проживання, оплати та скасування",
    role: "partner",
  },
  {
    id: "P01D",
    slug: "partner-wifi",
    title: "Wi-Fi",
    shortTitle: "Wi-Fi",
    description: "Мережа та пароль для гостей",
    role: "partner",
  },
  {
    id: "P01E",
    slug: "partner-contacts",
    title: "Контакти",
    shortTitle: "Контакти",
    description: "Телефони, месенджери, email, сайт і соціальні мережі",
    role: "partner",
  },
  {
    id: "P01F",
    slug: "partner-statistics",
    title: "Статистика переходів",
    shortTitle: "Статистика",
    description: "Переходи та джерела трафіку закладу",
    role: "partner",
  },
  {
    id: "P01G",
    slug: "partner-update",
    title: "Оновити інформацію",
    shortTitle: "Оновлення",
    description: "Оновлення анкети та даних закладу",
    role: "partner",
  },
  {
    id: "P01H",
    slug: "partner-cabinet",
    title: "Кабінет партнера",
    shortTitle: "Кабінет",
    description: "Головний екран активованого партнера",
    role: "partner",
  },
  {
    id: "P01I",
    slug: "partner-services",
    title: "Послуги закладу",
    shortTitle: "Послуги",
    description: "Керування послугами закладу",
    role: "partner",
  },
  {
    id: "P01I1",
    slug: "partner-services-hidden",
    title: "Сховані послуги",
    shortTitle: "Сховані",
    description: "Сховані та вимкнені послуги закладу",
    role: "partner",
  },
  {
    id: "P01I2",
    slug: "partner-service-add",
    title: "Додати послугу",
    shortTitle: "Додати послугу",
    description: "Створення нової послуги закладу",
    role: "partner",
  },
  {
    id: "P01I3",
    slug: "partner-service-category",
    title: "Категорія послуги",
    shortTitle: "Категорія",
    description: "Вибір категорії послуги",
    role: "partner",
  },
  {
    id: "P01I4",
    slug: "partner-service-price-type",
    title: "Тип ціни",
    shortTitle: "Тип ціни",
    description: "Вибір типу ціни нової послуги",
    role: "partner",
  },
  {
    id: "P01I5",
    slug: "partner-service-edit",
    title: "Редагування послуги",
    shortTitle: "Редагування",
    description: "Редагування параметрів послуги",
    role: "partner",
  },
  {
    id: "P01I6",
    slug: "partner-service-edit-price-type",
    title: "Тип ціни",
    shortTitle: "Тип ціни",
    description: "Зміна типу ціни послуги",
    role: "partner",
  },
  {
    id: "P01I6A",
    slug: "partner-service-edit-category",
    title: "Категорія послуги",
    shortTitle: "Категорія",
    description: "Зміна категорії послуги",
    role: "partner",
  },
  {
    id: "P01I7",
    slug: "partner-service-schedule-type",
    title: "Тип графіку",
    shortTitle: "Графік",
    description: "Вибір типу графіку послуги",
    role: "partner",
  },
  {
    id: "P01I8",
    slug: "partner-service-break",
    title: "Додати перерву",
    shortTitle: "Перерва",
    description: "Налаштування перерви в графіку послуги",
    role: "partner",
  },
  {
    id: "P01J",
    slug: "partner-checkin",
    title: "Час заїзду-виїзду",
    shortTitle: "Заїзд / виїзд",
    description: "Час заїзду та виїзду гостей",
    role: "partner",
  },

  {
    id: "P02",
    slug: "scanner",
    title: "Сканер QR клієнта",
    shortTitle: "Сканер QR",
    description: "Нативне сканування й перевірка короткоживучого токена",
    role: "partner",
  },
  {
    id: "P03",
    slug: "new-operation",
    title: "Нова операція",
    shortTitle: "Нова операція",
    description: "Сума, бонуси, комісія та запит підтвердження клієнту",
    role: "partner",
  },
  {
    id: "P04",
    slug: "calendar",
    title: "Календар бронювань",
    shortTitle: "Календар",
    description: "Ресурси, слоти, ручні записи та контроль конфліктів",
    role: "partner",
  },
  {
    id: "P05",
    slug: "booking-details",
    title: "Картка бронювання",
    shortTitle: "Картка бронювання",
    description: "Клієнт, ресурс, статус, контакт, перенесення й скасування",
    role: "partner",
  },
  {
    id: "P06",
    slug: "place-editor",
    title: "Редактор закладу",
    shortTitle: "Редактор закладу",
    description: "Шаблон, контент, фото, послуги, графік і ресурси",
    role: "partner",
  },
  {
    id: "P07",
    slug: "reviews-offers",
    title: "Відгуки й акції",
    shortTitle: "Відгуки й акції",
    description: "Відповіді, скарги, промо та вільні слоти",
    role: "partner",
  },
  {
    id: "P08",
    slug: "partner-finance",
    title: "Фінанси партнера",
    shortTitle: "Фінанси",
    description: "Statement, борг, компенсації, виплати й період звіту",
    role: "partner",
  },

  {
    id: "A01",
    slug: "ambassador-dashboard",
    title: "Кабінет амбасадора",
    shortTitle: "Dashboard",
    description: "QR, посилання, валідні залучення і винагорода",
    role: "ambassador",
  },
  {
    id: "A02",
    slug: "ambassador-campaigns",
    title: "Кампанії амбасадора",
    shortTitle: "Кампанії",
    description: "First-touch атрибуція, джерела і статуси винагород",
    role: "ambassador",
  },

  {
    id: "R01",
    slug: "regional-dashboard",
    title: "Регіональна адмінка",
    shortTitle: "Dashboard регіону",
    description: "Локальна статистика, партнери, QR і стан модерації",
    role: "regional",
  },
  {
    id: "R02",
    slug: "regional-partners",
    title: "Партнери регіону",
    shortTitle: "Партнери регіону",
    description: "Модерація й керування лише у дозволеному регіоні",
    role: "regional",
  },
  {
    id: "R03",
    slug: "regional-content",
    title: "Локальний контент",
    shortTitle: "Контент регіону",
    description: "Категорії, добірки, маршрути та актуальність даних",
    role: "regional",
  },

  {
    id: "AD01",
    slug: "admin-partners",
    title: "Партнери",
    shortTitle: "Партнери",
    description: "Список, фільтри, створення та картки партнерів",
    role: "admin",
  },
  {
    id: "AD02",
    slug: "admin-clients",
    title: "Клієнти",
    shortTitle: "Клієнти",
    description: "Список клієнтів, профілі, бонуси та активність",
    role: "admin",
  },
  {
    id: "AD03",
    slug: "admin-settlements",
    title: "Взаєморозрахунки",
    shortTitle: "Взаєморозрахунки",
    description: "Рахунки, борги та платежі партнерів",
    role: "admin",
  },
  {
    id: "AD04",
    slug: "admin-bonuses",
    title: "Бонуси",
    shortTitle: "Бонуси",
    description: "Бонусний баланс, нарахування та використання",
    role: "admin",
  },
  {
    id: "AD05",
    slug: "admin-statistics",
    title: "Статистика",
    shortTitle: "Статистика",
    description: "Огляд показників платформи",
    role: "admin",
  },
  {
    id: "AD06",
    slug: "admin-settings",
    title: "Налаштування",
    shortTitle: "Налаштування",
    description: "Системні налаштування адміністративної панелі",
    role: "admin",
  },
  {
    id: "ADP01",
    slug: "admin-partner-create",
    title: "Створення партнера",
    shortTitle: "Створення партнера",
    description: "Створення нового партнера",
    role: "admin",
  },
  {
    id: "ADP02",
    slug: "admin-partner-details",
    title: "Картка партнера",
    shortTitle: "Картка партнера",
    description: "Дані партнера та статистика",
    role: "admin",
  },
  {
    id: "ADP03",
    slug: "admin-partner-history",
    title: "Історія партнера",
    shortTitle: "Історія партнера",
    description: "Взаєморозрахунки, бонуси та активність партнера",
    role: "admin",
  },
  {
    id: "ADC01",
    slug: "admin-client-details",
    title: "Картка клієнта",
    shortTitle: "Картка клієнта",
    description: "Дані, бонуси та статистика клієнта",
    role: "admin",
  },
  {
    id: "ADC02",
    slug: "admin-client-history",
    title: "Історія клієнта",
    shortTitle: "Історія клієнта",
    description: "Історія бонусів та активності клієнта",
    role: "admin",
  },
  {
    id: "ADS01",
    slug: "admin-statistics-partners",
    title: "Статистика — Партнери",
    shortTitle: "Статистика партнерів",
    description: "Аналітика партнерів",
    role: "admin",
  },
  {
    id: "ADS02",
    slug: "admin-statistics-clients",
    title: "Статистика — Клієнти",
    shortTitle: "Статистика клієнтів",
    description: "Аналітика клієнтів",
    role: "admin",
  },
  {
    id: "ADS03",
    slug: "admin-statistics-bonuses",
    title: "Статистика — Бонуси",
    shortTitle: "Статистика бонусів",
    description: "Аналітика бонусів",
    role: "admin",
  },
  {
    id: "ADS04",
    slug: "admin-statistics-settlements",
    title: "Статистика — Розрахунки",
    shortTitle: "Статистика розрахунків",
    description: "Аналітика рахунків та платежів",
    role: "admin",
  },
  {
    id: "ADSET01",
    slug: "admin-settings-general",
    title: "Налаштування — Загальні",
    shortTitle: "Загальні",
    description: "Загальні параметри системи",
    role: "admin",
  },
  {
    id: "ADSET02",
    slug: "admin-settings-company",
    title: "Налаштування — Компанія",
    shortTitle: "Компанія",
    description: "Дані компанії та брендування",
    role: "admin",
  },
  {
    id: "ADSET03",
    slug: "admin-settings-partners",
    title: "Налаштування — Партнери та комісії",
    shortTitle: "Партнери та комісії",
    description: "Комісії, типи та статуси партнерів",
    role: "admin",
  },
  {
    id: "ADSET04",
    slug: "admin-settings-bonuses",
    title: "Налаштування — Бонусна система",
    shortTitle: "Бонусна система",
    description: "Правила бонусної програми",
    role: "admin",
  },
  {
    id: "ADSET05",
    slug: "admin-settings-notifications",
    title: "Налаштування — Сповіщення",
    shortTitle: "Сповіщення",
    description: "Канали й типи сповіщень",
    role: "admin",
  },
  {
    id: "ADSET06",
    slug: "admin-settings-security",
    title: "Налаштування — Безпека",
    shortTitle: "Безпека",
    description: "Безпека входу та сесій",
    role: "admin",
  },
  {
    id: "ADSET07",
    slug: "admin-settings-integrations",
    title: "Налаштування — Інтеграції",
    shortTitle: "Інтеграції",
    description: "Інтеграції та API",
    role: "admin",
  },
  {
    id: "ADSET08",
    slug: "admin-settings-audit",
    title: "Налаштування — Журнал дій",
    shortTitle: "Журнал дій",
    description: "Журнал дій адміністраторів",
    role: "admin",
  },

];

export const screensForRole = (role: RoleKey) =>
  screens.filter((screen) => screen.role === role);

export const defaultScreenForRole = (role: RoleKey) =>
  screensForRole(role)[0]?.slug ?? "welcome";

export const getScreen = (role: RoleKey, slug: string) =>
  screens.find((screen) => screen.role === role && screen.slug === slug) ??
  screens.find(
    (screen) =>
      screen.role === role && screen.slug === defaultScreenForRole(role),
  ) ??
  screens[0];
